# Generated by Django 3.1.3 on 2022-11-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('card_num', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
                ('card_pw', models.IntegerField()),
                ('loss', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CProduct',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'c_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_num', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'deposit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DProduct',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('limited', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10)),
                ('kind', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'd_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LProduct',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('limited', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10)),
                ('kind', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transation',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.IntegerField()),
                ('account', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=30)),
                ('remain', models.IntegerField(blank=True, null=True)),
                ('details', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('pw', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=50)),
            ],
        ),
    ]
