# Generated by Django 3.1.3 on 2022-11-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
