# Generated by Django 3.1.3 on 2022-11-09 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sota', '0002_auto_20221109_1034'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
