# Generated by Django 3.1.3 on 2022-11-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sota', '0003_auto_20221109_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CProduct',
        ),
    ]
