# Generated by Django 3.1.3 on 2022-11-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sota', '0004_delete_cproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CProduct',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('benefit', models.IntegerField()),
            ],
            options={
                'db_table': 'c_product',
                'managed': False,
            },
        ),
    ]
